import type { NextApiRequest, NextApiResponse } from 'next';

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  // Paste the JWT from the dashboard generator here
  const dashboardJwt = 'eyJraWQiOiJ2cGFhcy1tYWdpYy1jb29raWUtN2U4NWQzMDVjMGZkNDJjZGEyNDA3Mjk5OGY5YmE1YWEvMDNkMmVjLVNBTVBMRV9BUFAiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJqaXRzaSIsImlzcyI6ImNoYXQiLCJpYXQiOjE3NzQwNDM3MjQsImV4cCI6MTc3NDA1MDkyNCwibmJmIjoxNzc0MDQzNzE5LCJzdWIiOiJ2cGFhcy1tYWdpYy1jb29raWUtN2U4NWQzMDVjMGZkNDJjZGEyNDA3Mjk5OGY5YmE1YWEiLCJjb250ZXh0Ijp7ImZlYXR1cmVzIjp7ImxpdmVzdHJlYW1pbmciOnRydWUsImZpbGUtdXBsb2FkIjp0cnVlLCJvdXRib3VuZC1jYWxsIjp0cnVlLCJzaXAtb3V0Ym91bmQtY2FsbCI6ZmFsc2UsInRyYW5zY3JpcHRpb24iOnRydWUsImxpc3QtdmlzaXRvcnMiOmZhbHNlLCJyZWNvcmRpbmciOnRydWUsImZsaXAiOmZhbHNlfSwidXNlciI6eyJoaWRkZW4tZnJvbS1yZWNvcmRlciI6ZmFsc2UsIm1vZGVyYXRvciI6dHJ1ZSwibmFtZSI6ImthbmlzaGtrYjE4IiwiaWQiOiJnb29nbGUtb2F1dGgyfDEwOTg4MjUwNzE0OTQzODc0NTE3NiIsImF2YXRhciI6IiIsImVtYWlsIjoia2FuaXNoa2tiMThAZ21haWwuY29tIn19LCJyb29tIjoiKiJ9.gjpsHI6G1WjROqiXwRx-fyzTO9XpyO0eSlKlgQsRW3Q9oupfM7JJ6Ge4Bb-OMs8otbFz9aBUnt1rJ2vEKScKjj9HI58wCqyZiLNg0QI4TzovgAxE_1SJt5D7nAFyDPhn8l5aJaTu6ZXAXZhXRA5UGONRCTbPCol953ONr3aGHjhCaXyXF8KUzULp3ev2xAwda-ETuDx5scZHEXMc9EgoZQzPuAUUPhRzpNmMApBqtXQap_WTOoZ1tJpVebFz8DjUx5PI4Ck5ZrOs4W_CK5RY6V3ZqcSKqqf9aAq4gLIpJ6VKZN5k8G_BHDI5IJNkLXX5TfFWOQY2hmRcjBaI4LdDGg';
  const appId = process.env.NEXT_PUBLIC_JAAS_APP_ID!;

  res.json({
    jwt: dashboardJwt,
    roomName: `${appId}/testroom`,
    appId,
  });
}