import { prisma } from '../prisma';
import { contextManager } from '../context/manager';

const BAAS_API_KEY = process.env.MEETING_BAAS_API_KEY!;
const BAAS_BASE_URL = 'https://api.meetingbaas.com';

export interface ScheduleMeetingInput {
  title: string;
  participants: string[];
  dateTime: string;
  duration?: number;
  description?: string;
  platform?: 'google_meet' | 'zoom' | 'teams';
  deployBot?: boolean;
  userId: string;
}

export class MeetingTool {
  async scheduleMeeting(input: ScheduleMeetingInput) {
    const context = await contextManager.getContext(input.userId);
    
    // Parse participants (emails or names)
    const participantEmails: string[] = [];
    
    for (const p of input.participants) {
      if (p.includes('@')) {
        participantEmails.push(p);
      } else {
        const user = await prisma.user.findFirst({
          where: {
            OR: [
              { name: { contains: p, mode: 'insensitive' } },
              { email: { contains: p, mode: 'insensitive' } },
            ],
          },
        });
        if (user && user.email) {
          participantEmails.push(user.email);
        }
      }
    }

    const startTime = this.parseDateTime(input.dateTime);
    
    // Create meeting using your existing Meeting model
    const meeting = await prisma.meeting.create({
      data: {
        title: input.title,
        description: input.description,
        startTime,
        endTime: new Date(startTime.getTime() + (input.duration || 30) * 60000),
        userId: input.userId,
        eventId: '', // You may need to create an Event first or adjust schema
        guestName: input.title,
        guestEmail: participantEmails[0] || '',
        meetLink: '', // Will be generated by calendar integration
        calendarEventId: '',
        calendarAppType: input.platform || 'google_meet',
      },
    });

    // Deploy bot if requested
    if (input.deployBot) {
      await this.scheduleBot(meeting.id, meeting.meetLink || '', startTime);
    }

    return {
      success: true,
      meeting,
      message: `Scheduled "${meeting.title}" for ${startTime.toLocaleString()}`,
    };
  }

  private parseDateTime(dateStr: string): Date {
    const now = new Date();
    const lower = dateStr.toLowerCase();
    
    if (lower.includes('tomorrow')) {
      const date = new Date(now);
      date.setDate(date.getDate() + 1);
      const timeMatch = lower.match(/(\d+):?(\d*)\s*(am|pm)?/);
      if (timeMatch) {
        let hours = parseInt(timeMatch[1]);
        const minutes = parseInt(timeMatch[2] || '0');
        if (timeMatch[3] === 'pm' && hours !== 12) hours += 12;
        date.setHours(hours, minutes, 0, 0);
      } else {
        date.setHours(10, 0, 0, 0);
      }
      return date;
    }
    
    if (lower.includes('in 1 hour') || lower.includes('in an hour')) {
      return new Date(now.getTime() + 60 * 60 * 1000);
    }
    
    const parsed = new Date(dateStr);
    if (!isNaN(parsed.getTime())) return parsed;
    
    return new Date(now.getTime() + 60 * 60 * 1000);
  }

  private async scheduleBot(meetingId: string, meetLink: string, startTime: Date) {
    // Deploy immediately or schedule via your existing system
    const delay = startTime.getTime() - Date.now() - 2 * 60 * 1000;
    
    if (delay <= 0) {
      await this.deployBot(meetingId, meetLink);
    }
    // else schedule via cron/queue
  }

  async deployBot(meetingId: string, meetLink: string) {
    try {
      const response = await fetch(`${BAAS_BASE_URL}/bots`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${BAAS_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          meeting_url: meetLink,
          bot_name: 'Conferio Notetaker',
          recording_mode: 'speaker_view',
          speech_to_text: { provider: 'Default' },
        }),
      });

      if (!response.ok) throw new Error('Failed to deploy bot');

      const data = await response.json();
      
      // Update your AiMeeting model
      await prisma.aiMeeting.create({
        data: {
          userId: '', // Get from meeting
          meetingUrl: meetLink,
          botId: data.bot_id,
          status: 'joined',
        },
      });

      return { success: true, botId: data.bot_id };
    } catch (error) {
      throw error;
    }
  }

  async joinMeetingNow(meetingId: string, userId: string) {
    const meeting = await prisma.meeting.findFirst({
      where: { id: meetingId, userId },
    });
    
    if (!meeting?.meetLink) {
      throw new Error('Meeting not found or no link available');
    }

    return this.deployBot(meetingId, meeting.meetLink);
  }
}

export const meetingTool = new MeetingTool();
